### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by hawkkiller** [hawkkiller/midjourney_client#7]

**Comment by koko7753** [comment]
hi there is a video or image tutorial available on how to use it ?

**Comment by hawkkiller** [comment]
> hawkkiller/midjourney_client hi there is a video or image tutorial available on how to use it ?

Hi there. On Tue 20, Jun there will be a guide on how to run `imagine`, `variation`, `upscale`. I'm working on it. You may click `watch` for the repository in order to see all the updates.
Thanks.
